force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the answers provided for a question in the QA Forum app.</description>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/AnswerRating__c.field-meta.xml
<CustomField>
    <fullName>AnswerRating__c</fullName>
    <description>Field to capture the rating for an answer.</description>
    <label>Rating</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field to capture the description for an answer.</description>
    <inlineHelpText>Please provide a detailed description of the answer.</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Field to capture the parent Question for the answer being provided.</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Custom object to capture the questions asked in the QA forum.</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field for storing the description for a question.</description>
    <inlineHelpText>Describe your question for other users to understand the problem better.</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to provide the status of a question. A question is created in &apos;Open&apos; state by default.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vote_Record__c/Vote_Record__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the vote record for a record for a user.</description>
    <label>Vote Record</label>
    <nameField>
        <displayFormat>VR-{0000}</displayFormat>
        <label>Vote Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vote Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote_Record__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Field to store the API name of the object for which record is created.</description>
    <label>Object API Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vote_Record__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Field to store the Record Id of the record for which vote is stored.</description>
    <label>Record Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vote_Record__c/fields/User_Voted__c.field-meta.xml
<CustomField>
    <fullName>User_Voted__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to store the user information who voted on a record.</description>
    <label>User Voted</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vote_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote_Record__c/fields/Vote__c.field-meta.xml
<CustomField>
    <fullName>Vote__c</fullName>
    <description>Field to store the vote that a user made for the record.</description>
    <label>Vote</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upvote</fullName>
            </value>
            <value>
                <fullName>Downvote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RateAnswerController_TEST.cls
/**
 * @description Test class for RateAnswerController
 * 
 * @author vikrant.goswami
 * 
 * @date 11-05-2024 @see RateAnswerController
 */
@isTest
private class RateAnswerController_TEST {

    @testSetup
    static void testDataSetup() {
        //Create a new Question
        Question__c testQuestion = new Question__c(Name='Test Question', Description__c='Test Description for Test Question', Status__c='Open');
        insert testQuestion;
        // Create a test answer
        Answer__c testAnswer = new Answer__c(Name = 'Test Answer', Question__c=testQuestion.Id, Description__c='Test Description For Test Answer');
        insert testAnswer;

        // Create a test vote record for the test answer
        Vote_Record__c testVoteRecord = new Vote_Record__c(
            Object_API_Name__c='Anseer__c',
            Record_Id__c = testAnswer.Id,
            User_Voted__c = UserInfo.getUserId(),
            Vote__c = 'Upvote'
        );
        insert testVoteRecord;
        
    }

    static User createQaProfileUser() {
        Profile qaProfile = [SELECT Id, Name FROM Profile WHERE Name = 'QA Forum Users' ];
        User u = new User(FirstName='Test', LastName='Name', ProfileId=qaProfile.Id, Username='testuser@qa.test.com', 
                          Email='testuser@testmail.com', Alias='tname', TimeZoneSidKey='Asia/Kolkata', 
                          LocaleSidKey='en_IN', EmailEncodingKey='UTF-8',  
                          LanguageLocaleKey='en_US');
        insert u;
        return u;
    }

    @isTest
    static void testGetVoteRecordForCurrentUser() {

        Answer__c testAnswer = [SELECT Id, AnswerRating__c FROM Answer__c WHERE Name = 'Test Answer'];

        // Test method invocation
        Test.startTest();
        RateAnswerController.VoteRecordWrapper result = RateAnswerController.getVoteRecordForCurrentUser(testAnswer.Id, UserInfo.getUserId());
        Test.stopTest();

        // Assertion
        Assert.areEqual('Success', result.message, 'Not able to get the vote record');
        Assert.areEqual('Upvote', result.selectedVote);
    }

    @isTest
    static void testRecordVoteForUser() {

        Answer__c testAnswer = [SELECT Id, AnswerRating__c FROM Answer__c WHERE Name = 'Test Answer'];
        
        // Test method invocation
        Test.startTest();
        RateAnswerController.VoteInsertedWrapper result = RateAnswerController.recordVoteForUser(testAnswer.Id, UserInfo.getUserId(), 'Answer__c', 'Upvote', false);
        Test.stopTest();

        // Assertion
        Assert.areEqual('Success', result.message, 'Unable to record vote for user.');
        Assert.areEqual(false, result.insertionError);
    }
}