force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the answers provided for a question in the QA Forum app.</description>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/AnswerRating__c.field-meta.xml
<CustomField>
    <fullName>AnswerRating__c</fullName>
    <description>Field to capture the rating for an answer.</description>
    <label>Rating</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vote_Record__c/Vote_Record__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the vote record for a record for a user.</description>
    <label>Vote Record</label>
    <nameField>
        <displayFormat>VR-{0000}</displayFormat>
        <label>Vote Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vote Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote_Record__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Field to store the API name of the object for which record is created.</description>
    <label>Object API Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vote_Record__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Field to store the Record Id of the record for which vote is stored.</description>
    <label>Record Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vote_Record__c/fields/User_Voted__c.field-meta.xml
<CustomField>
    <fullName>User_Voted__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to store the user information who voted on a record.</description>
    <label>User Voted</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vote_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote_Record__c/fields/Vote__c.field-meta.xml
<CustomField>
    <fullName>Vote__c</fullName>
    <description>Field to store the vote that a user made for the record.</description>
    <label>Vote</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upvote</fullName>
            </value>
            <value>
                <fullName>Downvote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RateAnswerController.cls
/**
 * @description Controller class for getting and updating rating related information for an answer
 * 
 * @author vikrant.goswami
 * 
 * @date 10-05-2024 @see RateAnswerController_TEST
 */
public with sharing class RateAnswerController {

    /**
     * @description This method is used to get the voting record for a record and user
     * 
     * @param recordId The id of the record for which to get the voting record
     * @param userId The id of the user
     * 
     * @return The voting record wrapper
     */
    @AuraEnabled(cacheable=true)
    public static VoteRecordWrapper getVoteRecordForCurrentUser(String recordId, String userId) {
        VoteRecordWrapper voteRecordWrapper = new VoteRecordWrapper();
        try {
            Vote_Record__c voteRecord = [SELECT Id, Vote__c, User_Voted__c, Record_Id__c 
                                          FROM Vote_Record__c
                                          WHERE Record_Id__c = :recordId 
                                          AND User_Voted__c = :userId 
                                          ORDER BY CreatedDate DESC 
                                          LIMIT 1];
            if(voteRecord != null) {
                voteRecordWrapper.message = 'Success';
                voteRecordWrapper.selectedVote = voteRecord.Vote__c;
            } else {
                voteRecordWrapper.message = 'No vote record found';
            }
        } catch (QueryException exc) {
            voteRecordWrapper.message = 'Error: ' + exc.getMessage();
        }
        return voteRecordWrapper;
    }


    /**
     * @description This method is used to record a vote for a user on a record
     * 
     * @param recordId The id of the record for which to record the vote
     * @param userId The id of the user
     * @param objectApiName The API name of the object
     * @param voteSelected The vote selected (Upvote or Downvote)
     * @param alreadyVoted Indicates if the user has already voted on the record
     * 
     * @return The vote insertion wrapper
     */
    @AuraEnabled
    public static VoteInsertedWrapper recordVoteForUser(String recordId, String userId, String objectApiName, String voteSelected, Boolean alreadyVoted) {
        VoteInsertedWrapper voteInsertWrapper = new VoteInsertedWrapper();
        Savepoint sp = Database.setSavepoint();
        try {
            Answer__c answer = [SELECT Id, AnswerRating__c FROM Answer__c WHERE Id = :recordId];
            if (answer != null) {
                answer.AnswerRating__c = getCalculatedRating(answer.AnswerRating__c, voteSelected, alreadyVoted); 
                update answer;

                Vote_Record__c voteRecord = new Vote_Record__c(Object_API_Name__c = objectApiName, User_Voted__c = userId, Record_Id__c = recordId, Vote__c = voteSelected);
                insert voteRecord;

                voteInsertWrapper.message = 'Success';
            } else {
                voteInsertWrapper.message = 'Answer not found';
            }
        } catch (Exception exc) {
            Database.rollback(sp);
            voteInsertWrapper.insertionError = true;
            voteInsertWrapper.message = 'Error: ' + exc.getMessage();
        }
        return voteInsertWrapper;
    }

    private static Decimal getCalculatedRating(Decimal answerRating, String voteSelected, Boolean alreadyVoted) {
        if(voteSelected == 'Upvote') {
            answerRating = (alreadyVoted == true) ? answerRating + 2 : answerRating + 1;
        } else {
            answerRating = (alreadyVoted == true) ? answerRating - 2 : answerRating - 1;
        }
        return answerRating;
    }

    @TestVisible
    private class VoteRecordWrapper {
        @AuraEnabled 
        public String message {get;set;}

        @AuraEnabled 
        public String selectedVote {get;set;}
    }

    @TestVisible
    private class VoteInsertedWrapper {
        @AuraEnabled 
        public Boolean insertionError {get;set;}

        @AuraEnabled 
        public String message {get;set;}
    }        
}